version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: marketplace-api
    image: marketplace-api
    platform: linux/amd64
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: local-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marketplace
    ports:
      - "5439:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local